# Generated by Django 2.0.2 on 2018-04-30 00:10

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=django_mysql.models.ListCharField(models.CharField(default='my_directory', max_length=10, null=True), default='my_directory', max_length=66, size=6),
            preserve_default=False,
        ),
    ]
