# Generated by Django 2.0.2 on 2018-05-05 10:39

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='states',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='property.State'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=django_mysql.models.ListCharField(models.CharField(default='my_directory', max_length=10, null=True), max_length=500, size=6),
        ),
    ]
